check foo

diff --git a/ex/util/json b/ex/util/json
--- a/ex/util/json
+++ b/ex/util/json
@@ -1,29 +1,51 @@
 #!/bin/bash
 
-[ $# -lt 5 ] && . ex/util/throw 11 "Script needs more arguments, but actual is $#!"
-
-[ $(($(($# - 2)) % 3)) -ne 0 ] && . ex/util/throw 12 "Arguments error!"
+if test $# -lt 5; then
+ echo "Script needs more arguments, but actual is $#!"; exit 11
+elif test $(($(($# - 2)) % 3)) -ne 0; then
+ echo "Arguments error!"; exit 12
+fi
 
 JSON_SOURCE_OPTION="$1"
 JSON_SOURCE="$2"
+
+case "$JSON_SOURCE_OPTION" in
+ -j | --json)
+  if test -z "$JSON_SOURCE"; then
+   echo "Source is empty!"; exit 121
+  fi;;
+ -f | --file)
+  if [ ! -f "$JSON_SOURCE" ]; then
+   echo "File \"$JSON_SOURCE\" does not exist!"; exit 122
+  elif [ ! -s "$JSON_SOURCE" ]; then
+   echo "File \"$JSON_SOURCE\" is empty!"; exit 123
+  fi;;
+ *) echo "Source option \"$JSON_SOURCE_OPTION\" is not supported!"; exit 13;;
+esac
 
 VARIABLES=$(($(($# - 2)) / 3))
 for ((RELATIVE_INDEX=0; RELATIVE_INDEX<$VARIABLES; RELATIVE_INDEX++)); do
  JSON_QUERY_INDEX=$((2 + $((RELATIVE_INDEX * 3)) + 1))
  JSON_QUERY_OPTION="${!JSON_QUERY_INDEX}"
- . ex/util/require JSON_QUERY_OPTION
+ if test -z "$JSON_QUERY_OPTION"; then
+  echo "Query option is empty!"; exit 101
+ fi
  case "$JSON_QUERY_OPTION" in
   -sfs) JSON_OPTION="select((.!=null)and(type==\"string\")and(.!=\"\"))";;
   -si) JSON_OPTION="select((.!=null)and(type==\"number\"))";;
   -sb) JSON_OPTION="select((.!=null)and(type==\"boolean\"))";;
-  *) . ex/util/throw 21 "Query option \"$JSON_QUERY_OPTION\" is not supported!";;
+  *) echo "Query option \"$JSON_QUERY_OPTION\" is not supported!"; exit 21;;
  esac
  JSON_QUERY_INDEX=$((2 + $((RELATIVE_INDEX * 3)) + 2))
  JSON_QUERY="${!JSON_QUERY_INDEX}"
- . ex/util/require JSON_QUERY
+ if test -z "$JSON_QUERY"; then
+  echo "Query is empty!"; exit 102
+ fi
  JSON_QUERY_INDEX=$((2 + $((RELATIVE_INDEX * 3)) + 3))
  JSON_VARIABLE="${!JSON_QUERY_INDEX}"
- . ex/util/require JSON_VARIABLE
+ if test -z "$JSON_VARIABLE"; then
+  echo "Variable is empty!"; exit 103
+ fi
  JSON_CODE=0
  case "$JSON_SOURCE_OPTION" in
   -j | --json)
@@ -32,13 +54,17 @@ for ((RELATIVE_INDEX=0; RELATIVE_INDEX<$VARIABLES; RELATIVE_INDEX++)); do
   -f | --file)
    JSON_RESULT="$(jq -Mcer "${JSON_QUERY}|$JSON_OPTION" $JSON_SOURCE)"
    JSON_CODE=$?;;
-  *) . ex/util/throw 22 "Source option \"$JSON_SOURCE_OPTION\" is not supported!";;
+  *) echo "Source option \"$JSON_SOURCE_OPTION\" is not supported!"; exit 22;;
  esac
  if test "$JSON_QUERY_OPTION" == '-sb'; then
   if test $JSON_CODE -eq 0; then
-   [ "$JSON_RESULT" != 'true' ] && . ex/util/throw 31 "Unexpected boolean value \"$JSON_RESULT\"!"
+   if test "$JSON_RESULT" != 'true'; then
+    echo "Unexpected boolean value \"$JSON_RESULT\"!"; exit 31
+   fi
   elif test $JSON_CODE -eq 1; then
-   [ "$JSON_RESULT" != 'false' ] && . ex/util/throw 32 "Unexpected boolean value \"$JSON_RESULT\"!"
+   if test "$JSON_RESULT" != 'false'; then
+    echo "Unexpected boolean value \"$JSON_RESULT\"!"; exit 32
+   fi
    JSON_CODE=0
   fi
  fi
@@ -46,9 +72,9 @@ for ((RELATIVE_INDEX=0; RELATIVE_INDEX<$VARIABLES; RELATIVE_INDEX++)); do
   echo "Query option: \"$JSON_QUERY_OPTION\""
   echo "Variable: \"$JSON_VARIABLE\""
   case "$JSON_SOURCE_OPTION" in
-   -j | --json) . ex/util/throw 41 "Parse json error!";;
-   -f | --file) . ex/util/throw 42 "Parse \"$JSON_SOURCE\" error!";;
-   *) . ex/util/throw 43 "Source option \"$JSON_SOURCE_OPTION\" is not supported!";;
+   -j | --json) echo "Parse json error!"; exit 41;;
+   -f | --file) echo "Parse \"$JSON_SOURCE\" error!"; exit 42;;
+   *) echo "Source option \"$JSON_SOURCE_OPTION\" is not supported!"; exit 43;;
   esac
  fi
  printf -v "$JSON_VARIABLE" '%s' "$JSON_RESULT"
