fix util json

diff --git a/ex/util/json b/ex/util/json
--- a/ex/util/json
+++ b/ex/util/json
@@ -62,7 +62,10 @@ for ((RELATIVE_INDEX=0; RELATIVE_INDEX<$VARIABLES; RELATIVE_INDEX++)); do
    JSON_RESULT="$(jq -Mcer "${JSON_QUERY}|$JSON_OPTION" $JSON_SOURCE)"
    JSON_CODE=$?;;
   --base64)
-   JSON_RESULT="$(echo "$JSON_SOURCE" | base64 -d | jq -Mcer "${JSON_QUERY}|$JSON_OPTION")"
+   DECODED="$(echo "$JSON_SOURCE" | base64 -d)"; CODE=$?
+   if test $CODE -ne 0; then
+    echo "Decode base64 error!"; exit 23; fi
+   JSON_RESULT="$(echo "$DECODED" | jq -Mcer "${JSON_QUERY}|$JSON_OPTION")"
    JSON_CODE=$?;;
   *) echo "Source option \"$JSON_SOURCE_OPTION\" is not supported!"; exit 22;;
  esac
