check util mkdirs

diff --git a/ex/util/mkdirs b/ex/util/mkdirs
--- a/ex/util/mkdirs
+++ b/ex/util/mkdirs
@@ -10,17 +10,17 @@ for REQUIRE_ARGUMENT in MAKE_DIRECTORY
  do if test -z "${!REQUIRE_ARGUMENT}"; then
   echo "Argument \"$REQUIRE_ARGUMENT\" is empty!"; exit 12; fi done
 
-[ -d "$MAKE_DIRECTORY" ] && exit 0
-
-MAKE_CODE=0
-mkdir -p "$MAKE_DIRECTORY"; MAKE_CODE=$?
-
-if test $MAKE_CODE != 0; then
- echo "Make dir error!"
- exit 21
-fi
-
 if [ ! -d "$MAKE_DIRECTORY" ]; then
- echo "Dir \"$MAKE_DIRECTORY\" does not exist!"
- exit 22
+ MAKE_CODE=0
+ mkdir -p "$MAKE_DIRECTORY"; MAKE_CODE=$?
+
+ if test $MAKE_CODE != 0; then
+  echo "Make dir error!"
+  exit 21
+ fi
+
+ if [ ! -d "$MAKE_DIRECTORY" ]; then
+  echo "Dir \"$MAKE_DIRECTORY\" does not exist!"
+  exit 22
+ fi
 fi
