check util url

diff --git a/ex/util/url b/ex/util/url
--- a/ex/util/url
+++ b/ex/util/url
@@ -14,63 +14,63 @@ URL_TIMEOUT_MAX_DEFAULT=16
 URL_HEADERS=''
 
 for ((RELATIVE_INDEX=0; RELATIVE_INDEX<$(($# / 2)); RELATIVE_INDEX++)); do
- URL_OPTION_INDEX=$((RELATIVE_INDEX * 2 + 0))
- URL_VALUE_INDEX=$((RELATIVE_INDEX * 2 + 1))
+ URL_OPTION_INDEX=$((RELATIVE_INDEX * 2 + 1))
+ URL_VALUE_INDEX=$((RELATIVE_INDEX * 2 + 2))
  URL_OPTION="${!URL_OPTION_INDEX}"
  if test -z "$URL_OPTION"; then
-  echo "Url option is empty!"; exit $((30 + URL_OPTION_INDEX)); fi
+  echo "Url option is empty!"; exit $((30 + RELATIVE_INDEX + 1)); fi
  case "$URL_OPTION" in
   -u)
    if [ ! -z "$URL_BASE" ]; then
-    echo "Url is already set!"; exit $((50 + URL_OPTION_INDEX)); fi
+    echo "Url is already set!"; exit $((50 + RELATIVE_INDEX + 1)); fi
    URL_BASE="${!URL_VALUE_INDEX}"
    if test -z "$URL_BASE"; then
-    echo "Url is empty!"; exit $((60 + URL_OPTION_INDEX)); fi
+    echo "Url is empty!"; exit $((60 + RELATIVE_INDEX + 1)); fi
   ;;
   -o)
    if [ ! -z "$URL_OUTPUT" ]; then
-    echo "Url output is already set!"; exit $((70 + URL_OPTION_INDEX)); fi
+    echo "Url output is already set!"; exit $((70 + RELATIVE_INDEX + 1)); fi
    URL_OUTPUT="${!URL_VALUE_INDEX}"
    if test -z "$URL_OUTPUT"; then
-    echo "Url output is empty!"; exit $((80 + URL_OPTION_INDEX))
+    echo "Url output is empty!"; exit $((80 + RELATIVE_INDEX + 1))
    elif test -f "$URL_OUTPUT"; then
-    echo "Url \"$URL_OUTPUT\" exists!"; exit $((90 + URL_OPTION_INDEX))
+    echo "Url \"$URL_OUTPUT\" exists!"; exit $((90 + RELATIVE_INDEX + 1))
    fi
   ;;
   -e)
    if [ ! -z "$URL_CODE_EXPECTED" ]; then
-    echo "Url code expected already set!"; exit $((100 + URL_OPTION_INDEX)); fi
+    echo "Url code expected already set!"; exit $((100 + RELATIVE_INDEX + 1)); fi
    if [[ "${!URL_VALUE_INDEX}" =~ ^[1-9][0-9]*$ ]]; then
     URL_CODE_EXPECTED="${!URL_VALUE_INDEX}"
    else
-    echo "Url code expected format error!"; exit $((110 + URL_OPTION_INDEX))
+    echo "Url code expected format error!"; exit $((110 + RELATIVE_INDEX + 1))
    fi
   ;;
   -c)
    if [ ! -z "$URL_TIMEOUT_CONNECT" ]; then
-    echo "Url timeout connect already set!"; exit $((120 + URL_OPTION_INDEX)); fi
+    echo "Url timeout connect already set!"; exit $((120 + RELATIVE_INDEX + 1)); fi
    if [[ "${!URL_VALUE_INDEX}" =~ ^[1-9][0-9]*$ ]]; then
     URL_TIMEOUT_CONNECT="${!URL_VALUE_INDEX}"
    else
-    echo "Url timeout connect format error!"; exit $((130 + URL_OPTION_INDEX))
+    echo "Url timeout connect format error!"; exit $((130 + RELATIVE_INDEX + 1))
    fi
   ;;
   -m)
    if [ ! -z "$URL_TIMEOUT_MAX" ]; then
-    echo "Url timeout max already set!"; exit $((140 + URL_OPTION_INDEX)); fi
+    echo "Url timeout max already set!"; exit $((140 + RELATIVE_INDEX + 1)); fi
    if [[ "${!URL_VALUE_INDEX}" =~ ^[1-9][0-9]*$ ]]; then
     URL_TIMEOUT_MAX="${!URL_VALUE_INDEX}"
    else
-    echo "Url timeout max format error!"; exit $((150 + URL_OPTION_INDEX))
+    echo "Url timeout max format error!"; exit $((150 + RELATIVE_INDEX + 1))
    fi
   ;;
   -h)
    URL_HEADER="${!URL_VALUE_INDEX}"
    if test -z "$URL_HEADER"; then
-    echo "Url header is empty!"; exit $((160 + URL_OPTION_INDEX)); fi
+    echo "Url header is empty!"; exit $((160 + RELATIVE_INDEX + 1)); fi
    URL_HEADERS="$URL_HEADERS -H \"$URL_HEADER\""
   ;;
-  *) echo "Url option \"$URL_OPTION\" is not supported!"; exit $((40 + URL_OPTION_INDEX));;
+  *) echo "Url option \"$URL_OPTION\" is not supported!"; exit $((40 + RELATIVE_INDEX + 1));;
  esac
 done
 
@@ -83,19 +83,21 @@ if test -z "$URL_CODE_EXPECTED"; then
  URL_CODE_EXPECTED=$URL_CODE_EXPECTED_DEFAULT
 fi
 if test -z "$URL_TIMEOUT_CONNECT"; then
- URL_TIMEOUT_CONNECT=$URL_TIMEOUT_URL_TIMEOUT_CONNECT_DEFAULT
+ URL_TIMEOUT_CONNECT=$URL_TIMEOUT_CONNECT_DEFAULT
 fi
 if test -z "$URL_TIMEOUT_MAX"; then
- URL_TIMEOUT_MAX=$URL_TIMEOUT_URL_TIMEOUT_MAX_DEFAULT
+ URL_TIMEOUT_MAX=$URL_TIMEOUT_MAX_DEFAULT
 fi
 
 HTTP_CODE=0
-HTTP_CODE=$(
- /bin/bash -c "curl -s -w %{http_code} \
+HTTP_CODE=$(/bin/bash -c "curl -s -w %{http_code} \
   --connect-timeout $URL_TIMEOUT_CONNECT \
   -m $URL_TIMEOUT_MAX \
-  -o \"$URL_OUTPUT\" \"$URL_BASE\" $HEADERS")
-if test $HTTP_CODE -ne $URL_CODE_EXPECTED; then
- echo "Request error with response code \"$HTTP_CODE\"!"
- exit 91
+  -o \"$URL_OUTPUT\" \"$URL_BASE\" $URL_HEADERS")
+if test $? -ne 0; then
+ echo "Request \"$URL_BASE\" error!"
+ exit 201
+elif test $HTTP_CODE -ne $URL_CODE_EXPECTED; then
+ echo "Actual response code is \"$HTTP_CODE\", but expected is \"$URL_CODE_EXPECTED\"!"
+ exit 202
 fi
